---
groups:
  routers:
    replicasets:
      router:
        instances:
          router:
            roles_cfg:
              roles.httpd:
                srv_2:
                  listen: 8082
                srv_3:
                  listen: 8083
                default:
                  listen: 8081
    roles_cfg:
      roles.healthcheck:
        http:
        - endpoints:
          - path: /health-auto-0773
          - path: /health-auto-0774
          - path: /health-auto-0775
        - endpoints:
          - path: /health-auto-0776
          - path: /health-auto-0777
        - server: default
          endpoints:
          - path: /health-auto-0778
          - path: /health-auto-0779
        - server: default
          endpoints:
          - path: /health-auto-0780
          - path: /health-auto-0781
          - path: /health-auto-0782
        - endpoints: []
    roles:
    - roles.httpd
    - roles.healthcheck
credentials:
  users:
    replicator:
      password: secret
      roles:
      - replication
    client:
      password: secret
      roles:
      - super
iproto:
  listen:
  - uri: unix/:./{{ instance_name }}.iproto
  advertise:
    peer:
      login: replicator
replication:
  timeout: 0.1
...
