name: Linter

on:
  push:
  pull_request:

jobs:
  linter:
    if: |
      github.event_name == 'push' ||
      github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Setup Tarantool
      uses: tarantool/setup-tarantool@v4
      with:
        tarantool-version: '3.5.0'

    - name: Setup tt
      run: |
        curl -L https://tarantool.io/release/2/installer.sh | sudo bash
        sudo apt install -y tt
        tt version

    - name: Setup luacheck
      run: tt rocks install luacheck 0.25.0

    - name: Run luacheck
      run: make lint
